name = input("please enter your name: ")
surname = input("plese enter your surname: ")
age = int(input("please enter your age: "))
email = input("please enter your E-mail: ")
year_of_birth = int(input("please enter your year of birth: "))
Birthday = input("please enter your birthday: ")

print("you are "+name+"_"+ surname+"_"+str(age)+" years old")
print("your E-mail is "+ email)
print("you were born in "+str(year_of_birth)+", "+Birthday)
print("Congratulations, you have successfully registered.")